apiVersion: apps/v1
kind: Deployment
metadata:
  name: bbapp-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bbapp-backend
  template:
    metadata:
      labels:
        app: bbapp-backend
    spec:
      containers:
      - name: backend
        image: <AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/bbapp-backend:latest
        ports:
        - containerPort: 3000
        env: []
